services:
  - type: web
    name: qcrew
    runtime: node
    buildCommand: npm install && node reset_db.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
